cask_args appdir: "/Applications"

# Tap Homebrew
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/hashicorp"

cask "obs"
cask "visual-studio-code"
cask "firefox"
cask "vlc"
cask "wireshark"
cask "gimp"
cask "inkscape"
cask "amethyst"

# cask "jitsi-meet"
# cask "handbrake"
# cask "vagrant"
cask "spotify"
cask "raycast"

# System monitoring, trials
cask "macs-fan-control"
cask "istats-menu"
cask "turbo-boost-switcher"

# System
brew "zsh-completions"
brew "fzf"
brew "mas"
brew "curl"
brew "wget"
brew "git"
brew "vim"
brew "nvim"
brew "openssl"
brew "coreutils"
brew "moreutils"
brew "findutils"
brew "binutils"
brew "rename"
brew "gnu-sed"
brew "gnu-tar"
brew "gawk"
brew "gnutls"
brew "gnu-indent"
brew "gnu-getopt"
brew "tree"
brew "htop"
brew "pidof"
brew "pstree"
brew "grep"
brew "openssh"
brew "ripgrep"
brew "rsync"
brew "ssh-copy-id"
brew "screen"
brew "gmp"
brew "nmap"
brew "socat"
brew "rlwrap"
brew "dnstracer"
brew "sslscan"
brew "watch"

# Ops
brew "kind"
brew "ansible"
brew "tfenv"
brew "jsonnet"
brew "jsonnet-bundler"
brew "lima"

# Docker
brew "hadolint"

# AWS
brew "awscli"
brew "cfn-lint"

# Terraform
brew "tfenv"
brew "terraform-docs"
brew "terraform-ls"
brew "tflint"

# shellcheck
brew "shellcheck"

brew "node"

# Images, Audio, Video
brew "imagemagick"
brew "gifsicle"
brew "gifify"
brew "ffmpeg"

# Archive & Git
brew "xz"
brew "p7zip"
brew "git-lfs"

# Extract rpm file content with rpm2cpio *.rpm | cpio -ivd
brew "rpm2cpio"

# JSON
brew "jq"
brew "jo"

# Dev
# brew "ruby"
# brew "rbenv"
# brew "yarn"
brew "python"
brew "pyenv"
brew "pipenv"
brew "go"

# App Store
mas "1Password 7", id: 1333542190
mas "Slack", id: 803453959
mas "uBlock", id: 1385985095
mas "MindNode", id: 1289197285
mas "Slack", id: 803453959
mas "Notion Web Clipper", id: 1559269364
